import type {
  Grade,
  MathDomain,
  MathTopic,
  RepresentationType,
  SkillId,
} from '../types';
import { createSkillIndex } from './skillGraph';

export type GeneratorCapability =
  | 'number-identification'
  | 'counting'
  | 'number-comparison'
  | 'place-value'
  | 'fraction'
  | 'addition'
  | 'subtraction'
  | 'multiplication'
  | 'division'
  | 'operation-relations'
  | 'equality'
  | 'pattern'
  | 'measurement'
  | 'time'
  | 'money'
  | 'shape'
  | 'position'
  | 'classification'
  | 'data-table'
  | 'pictogram'
  | 'bar-chart'
  | 'data-interpretation';

export interface NumericRange {
  min: number;
  max: number;
}

export interface CanonicalSkillConstraints {
  valueRange?: NumericRange;
  resultRange?: NumericRange;
  allowedDenominators?: readonly number[];
}

export interface CanonicalSkillDefinition {
  id: SkillId;
  name: string;
  domain: MathDomain;
  topic: MathTopic;
  grades: readonly Grade[];
  prerequisites: readonly SkillId[];
  generatorCapability: GeneratorCapability;
  representations: readonly RepresentationType[];
  constraints?: CanonicalSkillConstraints;
}

const C = {
  concreteNumber: ['concrete', 'visual', 'symbolic'] as const,
  number: ['visual', 'symbolic', 'number-line'] as const,
  arithmetic: ['concrete', 'visual', 'symbolic', 'number-line'] as const,
  symbolicVisual: ['symbolic', 'visual'] as const,
  measure: ['concrete', 'visual', 'symbolic'] as const,
  shape: ['visual', 'concrete'] as const,
  data: ['visual', 'table'] as const,
};

export const canonicalSkillDefinitions = [
  {
    id: 'number_recognition_10',
    name: 'Recognize numbers to 10',
    domain: 'number',
    topic: 'number-sense',
    grades: [1],
    prerequisites: [],
    generatorCapability: 'number-identification',
    representations: C.concreteNumber,
    constraints: { valueRange: { min: 0, max: 10 } },
  },
  {
    id: 'count_objects_20',
    name: 'Count objects to 20',
    domain: 'number',
    topic: 'counting',
    grades: [1],
    prerequisites: ['number_recognition_10'],
    generatorCapability: 'counting',
    representations: ['concrete', 'visual'],
    constraints: { valueRange: { min: 0, max: 20 } },
  },
  {
    id: 'read_write_numbers_20',
    name: 'Read and write numbers to 20',
    domain: 'number',
    topic: 'number-sense',
    grades: [1],
    prerequisites: ['number_recognition_10'],
    generatorCapability: 'number-identification',
    representations: C.concreteNumber,
    constraints: { valueRange: { min: 0, max: 20 } },
  },
  {
    id: 'compare_order_numbers_20',
    name: 'Compare and order numbers to 20',
    domain: 'number',
    topic: 'comparison',
    grades: [1],
    prerequisites: ['count_objects_20', 'read_write_numbers_20'],
    generatorCapability: 'number-comparison',
    representations: C.number,
    constraints: { valueRange: { min: 0, max: 20 } },
  },
  {
    id: 'place_value_tens_ones',
    name: 'Understand tens and ones',
    domain: 'number',
    topic: 'place-value',
    grades: [1, 2],
    prerequisites: ['read_write_numbers_20'],
    generatorCapability: 'place-value',
    representations: C.concreteNumber,
    constraints: { valueRange: { min: 0, max: 99 } },
  },
  {
    id: 'compose_decompose_20',
    name: 'Compose and decompose numbers to 20',
    domain: 'number',
    topic: 'place-value',
    grades: [1],
    prerequisites: ['place_value_tens_ones'],
    generatorCapability: 'place-value',
    representations: C.concreteNumber,
    constraints: { valueRange: { min: 0, max: 20 } },
  },
  {
    id: 'read_write_numbers_100',
    name: 'Read and write numbers to 100',
    domain: 'number',
    topic: 'number-sense',
    grades: [1, 2],
    prerequisites: ['place_value_tens_ones'],
    generatorCapability: 'number-identification',
    representations: C.number,
    constraints: { valueRange: { min: 0, max: 100 } },
  },
  {
    id: 'compare_order_numbers_100',
    name: 'Compare and order numbers to 100',
    domain: 'number',
    topic: 'comparison',
    grades: [1, 2],
    prerequisites: ['read_write_numbers_100'],
    generatorCapability: 'number-comparison',
    representations: C.number,
    constraints: { valueRange: { min: 0, max: 100 } },
  },
  {
    id: 'place_value_hundreds',
    name: 'Understand hundreds, tens, and ones',
    domain: 'number',
    topic: 'place-value',
    grades: [2],
    prerequisites: ['place_value_tens_ones', 'read_write_numbers_100'],
    generatorCapability: 'place-value',
    representations: C.concreteNumber,
    constraints: { valueRange: { min: 0, max: 999 } },
  },
  {
    id: 'compose_decompose_100',
    name: 'Compose and decompose numbers to 100',
    domain: 'number',
    topic: 'place-value',
    grades: [2],
    prerequisites: ['place_value_tens_ones', 'read_write_numbers_100'],
    generatorCapability: 'place-value',
    representations: C.concreteNumber,
    constraints: { valueRange: { min: 0, max: 100 } },
  },
  {
    id: 'skip_count_2_5_10',
    name: 'Skip-count by 2, 5, and 10',
    domain: 'number',
    topic: 'counting',
    grades: [1, 2],
    prerequisites: ['read_write_numbers_100'],
    generatorCapability: 'counting',
    representations: C.number,
    constraints: { valueRange: { min: 0, max: 100 } },
  },
  {
    id: 'read_write_numbers_1000',
    name: 'Read and write numbers to 1,000',
    domain: 'number',
    topic: 'number-sense',
    grades: [3],
    prerequisites: ['place_value_hundreds'],
    generatorCapability: 'number-identification',
    representations: C.number,
    constraints: { valueRange: { min: 0, max: 1000 } },
  },
  {
    id: 'compare_order_numbers_1000',
    name: 'Compare and order numbers to 1,000',
    domain: 'number',
    topic: 'comparison',
    grades: [3],
    prerequisites: ['read_write_numbers_1000'],
    generatorCapability: 'number-comparison',
    representations: C.number,
    constraints: { valueRange: { min: 0, max: 1000 } },
  },
  {
    id: 'place_value_1000',
    name: 'Use place value within 1,000',
    domain: 'number',
    topic: 'place-value',
    grades: [3],
    prerequisites: ['place_value_hundreds', 'read_write_numbers_1000'],
    generatorCapability: 'place-value',
    representations: C.concreteNumber,
    constraints: { valueRange: { min: 0, max: 1000 } },
  },
  {
    id: 'compose_decompose_1000',
    name: 'Compose and decompose numbers to 1,000',
    domain: 'number',
    topic: 'place-value',
    grades: [3],
    prerequisites: ['place_value_1000'],
    generatorCapability: 'place-value',
    representations: C.concreteNumber,
    constraints: { valueRange: { min: 0, max: 1000 } },
  },
  {
    id: 'round_to_nearest_10',
    name: 'Round to the nearest 10',
    domain: 'number',
    topic: 'place-value',
    grades: [3],
    prerequisites: ['place_value_1000'],
    generatorCapability: 'place-value',
    representations: C.number,
    constraints: { valueRange: { min: 0, max: 1000 } },
  },
  {
    id: 'halves_and_quarters',
    name: 'Recognize halves and quarters as equal parts',
    domain: 'number',
    topic: 'fractions',
    grades: [1, 2],
    prerequisites: ['count_objects_20'],
    generatorCapability: 'fraction',
    representations: ['concrete', 'visual', 'symbolic'],
    constraints: { allowedDenominators: [2, 4] },
  },
  {
    id: 'unit_fractions',
    name: 'Recognize unit fractions',
    domain: 'number',
    topic: 'fractions',
    grades: [2, 3],
    prerequisites: ['halves_and_quarters'],
    generatorCapability: 'fraction',
    representations: ['concrete', 'visual', 'symbolic'],
    constraints: { allowedDenominators: [2, 3, 4, 5, 6, 8, 10] },
  },
  {
    id: 'compare_unit_fractions',
    name: 'Compare unit fractions',
    domain: 'number',
    topic: 'fractions',
    grades: [3],
    prerequisites: ['unit_fractions'],
    generatorCapability: 'fraction',
    representations: ['visual', 'symbolic', 'number-line'],
  },
  {
    id: 'equivalent_fractions_intro',
    name: 'Recognize simple equivalent fractions',
    domain: 'number',
    topic: 'fractions',
    grades: [3],
    prerequisites: ['unit_fractions'],
    generatorCapability: 'fraction',
    representations: ['visual', 'symbolic'],
  },

  {
    id: 'addition_concept',
    name: 'Understand addition as combining and adding to',
    domain: 'operations',
    topic: 'addition',
    grades: [1],
    prerequisites: ['number_recognition_10'],
    generatorCapability: 'addition',
    representations: C.arithmetic,
    constraints: { resultRange: { min: 0, max: 10 } },
  },
  {
    id: 'addition_within_10',
    name: 'Add within 10',
    domain: 'operations',
    topic: 'addition',
    grades: [1],
    prerequisites: ['addition_concept'],
    generatorCapability: 'addition',
    representations: C.arithmetic,
    constraints: { resultRange: { min: 0, max: 10 } },
  },
  {
    id: 'subtraction_concept',
    name: 'Understand subtraction as taking away and difference',
    domain: 'operations',
    topic: 'subtraction',
    grades: [1],
    prerequisites: ['number_recognition_10'],
    generatorCapability: 'subtraction',
    representations: C.arithmetic,
    constraints: { resultRange: { min: 0, max: 10 } },
  },
  {
    id: 'subtraction_within_10',
    name: 'Subtract within 10',
    domain: 'operations',
    topic: 'subtraction',
    grades: [1],
    prerequisites: ['subtraction_concept'],
    generatorCapability: 'subtraction',
    representations: C.arithmetic,
    constraints: { resultRange: { min: 0, max: 10 } },
  },
  {
    id: 'addition_within_20',
    name: 'Add within 20',
    domain: 'operations',
    topic: 'addition',
    grades: [1, 2],
    prerequisites: ['addition_within_10', 'compose_decompose_20'],
    generatorCapability: 'addition',
    representations: C.arithmetic,
    constraints: { resultRange: { min: 0, max: 20 } },
  },
  {
    id: 'subtraction_within_20',
    name: 'Subtract within 20',
    domain: 'operations',
    topic: 'subtraction',
    grades: [1, 2],
    prerequisites: ['subtraction_within_10', 'compose_decompose_20'],
    generatorCapability: 'subtraction',
    representations: C.arithmetic,
    constraints: { resultRange: { min: 0, max: 20 } },
  },
  {
    id: 'addition_within_100',
    name: 'Add within 100',
    domain: 'operations',
    topic: 'addition',
    grades: [2, 3],
    prerequisites: ['addition_within_20', 'place_value_tens_ones'],
    generatorCapability: 'addition',
    representations: C.arithmetic,
    constraints: { resultRange: { min: 0, max: 100 } },
  },
  {
    id: 'subtraction_within_100',
    name: 'Subtract within 100',
    domain: 'operations',
    topic: 'subtraction',
    grades: [2, 3],
    prerequisites: ['subtraction_within_20', 'place_value_tens_ones'],
    generatorCapability: 'subtraction',
    representations: C.arithmetic,
    constraints: { resultRange: { min: 0, max: 100 } },
  },
  {
    id: 'multiplication_equal_groups',
    name: 'Understand multiplication as equal groups',
    domain: 'operations',
    topic: 'multiplication',
    grades: [2],
    prerequisites: ['skip_count_2_5_10', 'addition_within_100'],
    generatorCapability: 'multiplication',
    representations: ['concrete', 'visual', 'symbolic'],
  },
  {
    id: 'division_sharing_grouping',
    name: 'Understand division as sharing and grouping',
    domain: 'operations',
    topic: 'division',
    grades: [2],
    prerequisites: ['multiplication_equal_groups'],
    generatorCapability: 'division',
    representations: ['concrete', 'visual', 'symbolic'],
  },
  {
    id: 'multiplication_facts_2_5_10',
    name: 'Use multiplication facts for 2, 5, and 10',
    domain: 'operations',
    topic: 'multiplication',
    grades: [2, 3],
    prerequisites: ['multiplication_equal_groups'],
    generatorCapability: 'multiplication',
    representations: C.symbolicVisual,
    constraints: { resultRange: { min: 0, max: 100 } },
  },
  {
    id: 'division_facts_2_5_10',
    name: 'Use related division facts for 2, 5, and 10',
    domain: 'operations',
    topic: 'division',
    grades: [2, 3],
    prerequisites: ['division_sharing_grouping', 'multiplication_facts_2_5_10'],
    generatorCapability: 'division',
    representations: C.symbolicVisual,
    constraints: { valueRange: { min: 0, max: 100 } },
  },
  {
    id: 'multiplication_facts_3_4',
    name: 'Use multiplication facts for 3 and 4',
    domain: 'operations',
    topic: 'multiplication',
    grades: [3],
    prerequisites: ['multiplication_facts_2_5_10'],
    generatorCapability: 'multiplication',
    representations: C.symbolicVisual,
    constraints: { resultRange: { min: 0, max: 100 } },
  },
  {
    id: 'division_facts_3_4',
    name: 'Use related division facts for 3 and 4',
    domain: 'operations',
    topic: 'division',
    grades: [3],
    prerequisites: ['division_facts_2_5_10', 'multiplication_facts_3_4'],
    generatorCapability: 'division',
    representations: C.symbolicVisual,
    constraints: { valueRange: { min: 0, max: 100 } },
  },
  {
    id: 'addition_within_1000',
    name: 'Add within 1,000',
    domain: 'operations',
    topic: 'addition',
    grades: [3],
    prerequisites: ['addition_within_100', 'place_value_1000'],
    generatorCapability: 'addition',
    representations: C.arithmetic,
    constraints: { resultRange: { min: 0, max: 1000 } },
  },
  {
    id: 'subtraction_within_1000',
    name: 'Subtract within 1,000',
    domain: 'operations',
    topic: 'subtraction',
    grades: [3],
    prerequisites: ['subtraction_within_100', 'place_value_1000'],
    generatorCapability: 'subtraction',
    representations: C.arithmetic,
    constraints: { resultRange: { min: 0, max: 1000 } },
  },
  {
    id: 'multiplication_division_inverse',
    name: 'Relate multiplication and division as inverse operations',
    domain: 'operations',
    topic: 'operation-relations',
    grades: [3],
    prerequisites: ['multiplication_facts_3_4', 'division_facts_3_4'],
    generatorCapability: 'operation-relations',
    representations: C.symbolicVisual,
  },

  {
    id: 'equality_symbol',
    name: 'Understand the equality symbol',
    domain: 'algebra',
    topic: 'equality',
    grades: [1, 2],
    prerequisites: ['addition_concept'],
    generatorCapability: 'equality',
    representations: C.symbolicVisual,
  },
  {
    id: 'missing_number_add_sub_within_20',
    name: 'Find a missing number in addition and subtraction within 20',
    domain: 'algebra',
    topic: 'equality',
    grades: [2],
    prerequisites: ['equality_symbol', 'addition_within_20', 'subtraction_within_20'],
    generatorCapability: 'equality',
    representations: C.symbolicVisual,
    constraints: { valueRange: { min: 0, max: 20 } },
  },
  {
    id: 'repeating_patterns',
    name: 'Recognize and continue repeating patterns',
    domain: 'algebra',
    topic: 'patterns',
    grades: [1, 2],
    prerequisites: [],
    generatorCapability: 'pattern',
    representations: ['visual', 'concrete', 'symbolic'],
  },
  {
    id: 'number_patterns_skip_counting',
    name: 'Recognize number patterns from skip-counting',
    domain: 'algebra',
    topic: 'patterns',
    grades: [2, 3],
    prerequisites: ['repeating_patterns', 'skip_count_2_5_10'],
    generatorCapability: 'pattern',
    representations: ['symbolic', 'visual', 'number-line'],
  },

  {
    id: 'compare_length',
    name: 'Compare lengths directly',
    domain: 'measurement',
    topic: 'length',
    grades: [1],
    prerequisites: [],
    generatorCapability: 'measurement',
    representations: ['concrete', 'visual'],
  },
  {
    id: 'compare_mass',
    name: 'Compare masses directly',
    domain: 'measurement',
    topic: 'mass',
    grades: [1],
    prerequisites: [],
    generatorCapability: 'measurement',
    representations: ['concrete', 'visual'],
  },
  {
    id: 'compare_duration',
    name: 'Compare durations',
    domain: 'measurement',
    topic: 'time',
    grades: [1],
    prerequisites: [],
    generatorCapability: 'time',
    representations: ['visual', 'concrete'],
  },
  {
    id: 'measure_nonstandard_length',
    name: 'Measure length with non-standard units',
    domain: 'measurement',
    topic: 'length',
    grades: [1, 2],
    prerequisites: ['compare_length', 'count_objects_20'],
    generatorCapability: 'measurement',
    representations: C.measure,
  },
  {
    id: 'measure_standard_length',
    name: 'Measure length with standard units',
    domain: 'measurement',
    topic: 'length',
    grades: [2, 3],
    prerequisites: ['measure_nonstandard_length', 'read_write_numbers_100'],
    generatorCapability: 'measurement',
    representations: C.measure,
  },
  {
    id: 'measure_standard_mass',
    name: 'Measure mass with standard units',
    domain: 'measurement',
    topic: 'mass',
    grades: [2, 3],
    prerequisites: ['compare_mass', 'read_write_numbers_100'],
    generatorCapability: 'measurement',
    representations: C.measure,
  },
  {
    id: 'tell_time_hour_half_hour',
    name: 'Tell time to the hour and half-hour',
    domain: 'measurement',
    topic: 'time',
    grades: [1, 2],
    prerequisites: ['compare_duration'],
    generatorCapability: 'time',
    representations: ['clock', 'visual', 'symbolic'],
  },
  {
    id: 'tell_time_5_minutes',
    name: 'Tell time to five-minute intervals',
    domain: 'measurement',
    topic: 'time',
    grades: [2, 3],
    prerequisites: ['tell_time_hour_half_hour', 'skip_count_2_5_10'],
    generatorCapability: 'time',
    representations: ['clock', 'visual', 'symbolic'],
  },
  {
    id: 'money_values_and_totals',
    name: 'Recognize money values and calculate simple totals',
    domain: 'measurement',
    topic: 'money',
    grades: [2, 3],
    prerequisites: ['addition_within_100'],
    generatorCapability: 'money',
    representations: ['money', 'visual', 'symbolic'],
  },

  {
    id: 'identify_2d_shapes',
    name: 'Identify common 2D shapes',
    domain: 'geometry',
    topic: '2d-shapes',
    grades: [1, 2],
    prerequisites: [],
    generatorCapability: 'shape',
    representations: C.shape,
  },
  {
    id: 'compose_decompose_2d_shapes',
    name: 'Compose and decompose 2D shapes',
    domain: 'geometry',
    topic: '2d-shapes',
    grades: [1, 2],
    prerequisites: ['identify_2d_shapes'],
    generatorCapability: 'shape',
    representations: C.shape,
  },
  {
    id: 'identify_3d_shapes',
    name: 'Identify common 3D shapes',
    domain: 'geometry',
    topic: '3d-shapes',
    grades: [1, 2],
    prerequisites: [],
    generatorCapability: 'shape',
    representations: C.shape,
  },
  {
    id: 'spatial_position',
    name: 'Describe relative position and direction',
    domain: 'geometry',
    topic: 'position',
    grades: [1, 2],
    prerequisites: [],
    generatorCapability: 'position',
    representations: ['visual', 'concrete'],
  },
  {
    id: 'describe_2d_shape_properties',
    name: 'Describe properties of common 2D shapes',
    domain: 'geometry',
    topic: '2d-shapes',
    grades: [2, 3],
    prerequisites: ['identify_2d_shapes'],
    generatorCapability: 'shape',
    representations: ['visual', 'symbolic'],
  },

  {
    id: 'sort_classify_objects',
    name: 'Sort and classify objects by attributes',
    domain: 'data',
    topic: 'classification',
    grades: [1],
    prerequisites: [],
    generatorCapability: 'classification',
    representations: ['concrete', 'visual'],
  },
  {
    id: 'tally_and_simple_tables',
    name: 'Organize simple data with tallies and tables',
    domain: 'data',
    topic: 'tables',
    grades: [1, 2],
    prerequisites: ['sort_classify_objects', 'count_objects_20'],
    generatorCapability: 'data-table',
    representations: ['table', 'visual'],
  },
  {
    id: 'pictograms_simple',
    name: 'Read and create simple pictograms',
    domain: 'data',
    topic: 'pictograms',
    grades: [1, 2],
    prerequisites: ['sort_classify_objects', 'count_objects_20'],
    generatorCapability: 'pictogram',
    representations: ['pictogram', 'visual'],
  },
  {
    id: 'bar_charts_unit_scale',
    name: 'Read and create unit-scale bar charts',
    domain: 'data',
    topic: 'bar-charts',
    grades: [3],
    prerequisites: ['tally_and_simple_tables', 'pictograms_simple', 'read_write_numbers_100'],
    generatorCapability: 'bar-chart',
    representations: ['bar-chart', 'table', 'visual'],
  },
  {
    id: 'interpret_simple_data',
    name: 'Compare and interpret simple data displays',
    domain: 'data',
    topic: 'tables',
    grades: [2, 3],
    prerequisites: ['tally_and_simple_tables', 'pictograms_simple'],
    generatorCapability: 'data-interpretation',
    representations: C.data,
  },
] as const satisfies readonly CanonicalSkillDefinition[];

export const canonicalSkills = createSkillIndex(
  canonicalSkillDefinitions,
) as Readonly<Record<SkillId, CanonicalSkillDefinition>>;
